name: Azure-Dotnet-Extensions Code Sync
on:
  # Manual run
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
    # Once per day at midnight PST (8 UTC)
    - cron: '0 8 * * *'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  compare_repos:
    # Comment out this line to test the scripts in a fork
    # if: github.repository == 'azure/dotnet-extensions-experimental'
    name: Sync shared code between Azure and DotNet
    runs-on: windows-latest
    steps:
    - name: Checkout Azure Extensions
      uses: actions/checkout@v3
      with:
        # Test this script using changes in a fork
        # repository: 'azure/dotnet-extensions-experimental'
        repository: 'tratcher/dotnet-extensions-experimental'
        path: azure-extensions
        ref: main
    - name: Checkout dotnet extensions
      uses: actions/checkout@v3
      with:
        # Test this script using changes in a fork
        repository: 'dotnet/extensions'
        path: dotnet-extensions
        ref: main
    - name: Copy
      shell: cmd
      working-directory: .\dotnet-extensions\src\Shared\AzureSync\
      env:
        AZUREEXTENSIONS_REPO: d:\a\dotnet-extensions-experimental\dotnet-extensions-experimental\azure-extensions\
      run: CopyToAzure.cmd
    - name: Diff
      shell: cmd
      working-directory: .\azure-extensions\
      run: |
        mkdir ..\artifacts
        git status > ..\artifacts\status.txt
        git diff > ..\artifacts\diff.txt
    - uses: actions/upload-artifact@v3
      with:
        name: results
        path: artifacts
    - name: Check and Notify
      id: check
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Test this script using an issue in the local forked repo
        # $issue = 'https://api.github.com/repos/azure/dotnet-extensions-experimental/issues/1'
        $issue = 'https://api.github.com/repos/tratcher/dotnet-extensions-experimental/issues/1'
        $sendpr = .\azure-extensions\.github\workflows\ReportDiff.ps1
        echo "sendpr=$sendpr" >> $env:GITHUB_OUTPUT
    - name: GIT commit and push all changed files
      if: steps.check.outputs.sendpr == 'true'
      shell: cmd
      working-directory: .\azure-extensions\
      env:
        CI_COMMIT_MESSAGE: Sync shared code from dotnet/extensions, Fixes #1.
        CI_COMMIT_AUTHOR: DotNet Sync - Github Actions
      # The prior powershell script created the branch
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "GithubActions@users.noreply.github.com"
        git config push.autoSetupRemote true
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push